<?php 
require( 'init.php' );
require('templates/head-home.php');
?>
<div id="hero">
    <h1>Welcome to this blog</h1>
</div>
<?php require('templates/header.php'); ?>
    <p class="home-p">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut malesuada neque sit amet tellus molestie, eget volutpat tortor porttitor. Sed fermentum eget tortor eu consequat. Donec sed eros interdum, laoreet massa ac, vestibulum ligula. Mauris euismod et turpis nec maximus. Sed convallis arcu justo, eget facilisis purus bibendum euismod. Curabitur euismod a nibh non aliquam. In hac habitasse platea dictumst. Aenean condimentum vitae odio in eleifend. Quisque interdum eget ipsum non sollicitudin. Phasellus blandit enim sed mauris iaculis, a dapibus sapien tincidunt. Nam blandit et lectus sit amet gravida. Cras et euismod felis. Integer scelerisque ut risus ac convallis. Etiam vitae mollis urna.

        Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam nec cursus nisi. Praesent ut nulla non libero tincidunt hendrerit sit amet scelerisque lectus. Phasellus mauris neque, cursus ac mollis sit amet, dictum non mi. Morbi orci tortor, efficitur ut leo eu, pretium accumsan leo. Vestibulum sagittis luctus tempor. Nunc ultrices, dolor ac mollis mattis, purus tortor bibendum lorem, sed consequat magna elit eu arcu. Quisque venenatis finibus sapien, vitae mollis metus faucibus vehicula.

        Nullam id porta diam. Mauris facilisis neque in fringilla lobortis. Maecenas efficitur turpis et justo condimentum suscipit. Donec facilisis tellus pharetra, mattis tellus id, dapibus nulla. Vestibulum a vehicula dolor. Sed ut purus sit amet est ornare imperdiet id eu purus. Nulla in eros eu metus rhoncus tincidunt eu non quam. Vivamus luctus sapien sit amet diam molestie dignissim. Donec vel nisl sit amet eros maximus porta. Nulla laoreet, ipsum ac eleifend cursus, lectus arcu congue augue, at cursus est libero non nisl.

        Mauris consequat urna vitae nulla pharetra maximus. Fusce pretium, magna sit amet aliquet fermentum, nibh enim semper mauris, sed sollicitudin mi justo sed tellus. Proin vehicula, diam eget accumsan posuere, enim turpis sollicitudin ex, pretium ullamcorper urna arcu eget odio. Vestibulum non ligula ut sem dapibus dapibus. Praesent auctor fermentum dui, sit amet semper eros suscipit ut. Nullam non gravida sapien, nec finibus sapien. Aliquam a arcu placerat, congue nisi a, eleifend tellus. Integer vitae sapien quis est convallis vehicula. Aenean ultrices massa vel rutrum maximus. Phasellus placerat massa elit, ut ornare nibh rutrum eu. Fusce lacus dui, pellentesque quis dapibus quis, interdum nec nulla.

        Phasellus varius facilisis urna sit amet sodales. Vestibulum eu interdum nisl. Curabitur nec lorem rhoncus enim interdum pharetra sed vitae ante. Cras purus ex, dapibus id massa non, blandit porta justo. Fusce euismod vestibulum vulputate. In tristique eget neque ut condimentum. Ut ut lacus ac quam pretium cursus. Maecenas mollis lectus ultrices, tristique leo nec, pulvinar eros. Aliquam et erat hendrerit, feugiat magna id, sodales ligula. Phasellus in volutpat nibh. Morbi et eleifend quam. Nullam varius vulputate convallis. Donec mollis feugiat lectus sed rutrum. Integer vel ligula euismod, tempus magna eu, sollicitudin purus.

        Quisque aliquet nisl sed est rutrum, sit amet iaculis nibh suscipit. Curabitur congue orci non tristique laoreet. Quisque bibendum lacinia ipsum, nec congue ligula. In pharetra, nunc sit amet dapibus ullamcorper, metus enim semper risus, ut accumsan nisi risus ut metus. Vivamus accumsan lacus quis erat egestas dapibus. Morbi suscipit bibendum laoreet. Donec vitae maximus arcu. Etiam euismod nisi leo, nec blandit velit ornare ut. Aliquam sed mattis libero. Praesent varius diam ac lorem imperdiet, sit amet volutpat turpis lobortis. Integer maximus aliquet lectus, id auctor justo consectetur id. Aliquam erat volutpat. Nunc scelerisque hendrerit eros, vitae facilisis ex luctus ut.

        Morbi arcu tellus, faucibus non velit viverra, rhoncus volutpat diam. Suspendisse sed nisi eget tortor scelerisque interdum. Nulla malesuada magna in diam blandit, eget auctor mauris dictum. Vestibulum lacus justo, vehicula quis imperdiet a, molestie ut ante. Ut ut pulvinar nisl, ultrices vehicula dolor. Donec leo lectus, tempor quis rhoncus at, accumsan vel tellus. Duis nisi neque, vulputate quis egestas quis, mattis nec nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec in gravida nibh, at mollis ex.

        Ut viverra tempus sapien quis vulputate. Proin ipsum nulla, luctus at consectetur id, dapibus a sem. In posuere felis eget iaculis eleifend. Ut imperdiet a diam et fermentum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc interdum, est vel tristique feugiat, sem lorem posuere massa, ac euismod ligula tellus eget magna. Nam a urna nisl. Nullam dictum leo diam, at sollicitudin magna tempor sed. Nunc accumsan ante nec blandit maximus.

        Aliquam ornare risus porta odio dapibus, vitae ornare odio consequat. Integer aliquam efficitur varius. Suspendisse sodales feugiat orci, non hendrerit justo tincidunt nec. Duis auctor, erat imperdiet cursus rhoncus, sem metus laoreet nisl, sit amet semper nisl nunc quis nisl. Fusce sit amet velit sit amet enim tempor malesuada. Nulla vitae justo in leo facilisis pharetra sed non magna. Quisque eu risus vitae tellus lacinia iaculis. Duis a efficitur elit. Fusce posuere elit consequat metus cursus vehicula. Integer bibendum purus vitae elit faucibus, sed lobortis massa pharetra. Pellentesque id diam rutrum, sodales elit eu, molestie lectus. Pellentesque non lorem tortor. Ut maximus tellus in faucibus euismod. Duis egestas metus sit amet elementum molestie.

        Donec turpis eros, ultricies et faucibus id, eleifend sed nibh. Nunc eleifend felis vel dui sodales, eget rhoncus velit ornare. Nam lacinia aliquet diam, eget dignissim magna feugiat nec. Phasellus auctor quam vitae tincidunt aliquam. Cras ac hendrerit libero, sed mollis velit. Morbi auctor tincidunt scelerisque. Donec pulvinar vulputate turpis. Nullam euismod urna vitae ante ornare suscipit. Pellentesque venenatis tortor faucibus, elementum ligula quis, porta nunc. Integer vitae nulla orci. Vivamus pellentesque mauris tempus ligula elementum iaculis. Integer velit nunc, venenatis ut pharetra sed, molestie eu urna. Vivamus et pharetra ante, eu imperdiet lectus. Suspendisse ultrices quam vel ante fringilla accumsan. Phasellus id condimentum dolor.
    </p>
<script src="<?php echo SITE_URL ;?>/assets/sticky.js"></script>
<?php require('templates/footer.php'); ?>